---
nginx_sites:
  default:
    - listen 80
    - server_name web01.dev
    - root "/usr/share/nginx/html"
    - index index.html
  elastic:
    - listen 80
    - server_name elastic.arthurjames.nl
    - |
      location / {
        proxy_pass http://10.6.0.192:9200;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded_For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded_Proto $scheme;
      }
  grafana:
    - listen 80
    - server_name grafana.arthurjames.nl
    - |
      location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded_For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded_Proto $scheme;
      }
  jenkins:
    - listen 80
    - server_name jenkins.arthurjames.nl
    - |
      location / {
        proxy_pass http://10.6.0.219:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded_For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded_Proto $scheme;
      }
  prometheus:
    - listen 80
    - server_name prometheus.arthurjames.nl
    - |
      location / {
        proxy_pass http://10.6.0.209:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded_For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded_Proto $scheme;
      }
