---
nginx_sites:
  default:
    - listen 80
    - server_name web01.dev
    - root "/usr/share/nginx/html"
    - index index.html
  grafana:
    - listen 80
    - server_name grafana.shelltapup.nl
    - |
      location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded_For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded_Proto $scheme;
      }
  jenkins:
    - listen 80
    - server_name jenkins.shelltapup.nl
    - |
      location / {
        proxy_pass http://10.6.0.219:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded_For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded_Proto $scheme;
      }
