---

- name: Configure monitoring server with elastic 
  hosts: elastic 
  become: yes
  become_user: root
  vars_files:
    - vars/elastic.yml

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=86400
      
  roles:
    - role: ansible-role-ntp
    - { role: ansible-elasticsearch, es_instance_name: "es01",
    es_config: {
    	network.bind_host: 0,
        http.cors.enabled: true,
        http.cors.allow-origin: "*"
        }
    }
