---

- name: Configure PostgreSQL database
  hosts: db
  become: yes
  become_user: root
  vars_files:
    - vars/postgresql.yml

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=86400
      
  roles:
    - role: postgresql 
